[package]
name = "strange-attractors"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_code_editor = "0.2.10"
nannou = "0.19.0"
nannou_egui = "0.19.0"
rhai = { version = "1.19.0", features = ["f32_float"] }
